VOCABULARY = {
    "COUNTRIES": [
        "ENGLAND", "SPAIN", "FRANCE", "PORTUGAL", "MEXICO", "GERMANY", "CANADA", 
        "ITALY", "AUSTRALIA", "BRAZIL", "ARGENTINA", "COLOMBIA", "UNITED KINGDOM", "NEW ZEALAND"
    ],
    "NATIONALITIES": [
        "ENGLISH", "AMERICAN", "SPANISH", "JAPANESE", "CHINESE", "FRENCH", "PORTUGUESE", 
        "MEXICAN", "GERMAN", "CANADIAN", "ITALIAN", "EGYPTIAN", "AUSTRALIAN", "BRAZILIAN", 
        "ARGENTINIAN", "DUTCH"
    ],

    "PAST_VERBS": [
        "WALKED", "PLAYED", "TRIED", "STUDIED", "CLEANED", "SENT", "RODE", "RAN", 
        "DROVE", "SLEPT", "MADE", "SPOKE", "ATE", "WENT", "WROTE", "LISTENED", 
        "SAW", "LAUGHED", "WANTED", "COOKED", "DANCED", "TYPED", "WAITED", 
        "PAINTED", "NEEDED", "HUNTED", "VISITED", "HATED", "SHOUTED"
    ],

    "CLOTHES": [
        "T SHIRT", "SHIRT", "SKIRT", "DRESS", "PANTS", "SHORTS", "CAP", "HAT", 
        "GLOVES", "CLOTHES", "SUNGLASSES", "SCARF", "BOOTS", "JACKET", "COAT", 
        "SHOES", "SNEAKERS", "SANDALS", "FLIP FLOPS", "SWEATER", "BELT", "SOCKS"
    ],

    "DAYS_OF_WEEK": [
        "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"
    ],

    "COLORS": [
        "RED", "BLUE", "GREEN", "YELLOW", "ORANGE", "PURPLE", "PINK", "BLACK", 
        "WHITE", "BROWN", "GRAY"
    ],

    "JOBS": [
        "HOUSEWIFE", "TEACHER", "DENTIST", "DRIVER", "POLICE OFFICER", "ARCHITECT", 
        "ARTIST", "FLIGHT ATTENDANT", "MECHANIC", "NURSE", "BUTCHER", "SALESPERSON", 
        "PHARMACIST", "SECRETARY", "WATCHMAN", "BAKER", "LAWYER", "ENGINEER", 
        "PLUMBER", "CARPENTER", "PHOTOGRAPHER", "MAID", "MANAGER"
    ],

    "HOUSE_FURNITURE": [
        "KITCHEN", "DOOR", "FLOOR", "DINING ROOM", "BACKYARD", "SOFA", "CHAIR", 
        "TABLE", "CABINET", "MIRROR", "BED", "BEDROOM", "SINK", "REFRIGERATOR", 
        "STOVE", "OVEN", "RUG", "NIGHTSTAND", "SHELF", "WARDROBE", "PICTURE", 
        "GLASS", "WALL", "MICROWAVE", "TOILET", "FAUCET"
    ],

    "MONTHS": [
        "JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", 
        "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER"
    ],

    "ORDINAL_NUMBERS": [
        "FIRST", "SECOND", "THIRD", "FOURTH", "FIFTH", "SIXTH", "SEVENTH", 
        "EIGHTH", "NINTH", "TENTH", "ELEVENTH", "TWELFTH", "THIRTEENTH", 
        "FOURTEENTH", "FIFTEENTH", "SIXTEENTH", "SEVENTEENTH", "EIGHTEENTH", 
        "NINETEENTH", "TWENTIETH"
    ],

    "WEATHER": [
        "SUNNY", "CLOUDY", "WINDY", "RAINY", "SNOWY", "WARM", "COLD", "HOT", "NICE"
    ],

    "FOOD": [
        "BEANS", "BROCCOLI", "CARROTS", "CORN", "CUCUMBER", "GARLIC", "GREEN BEANS", 
        "LETTUCE", "OLIVE", "ONION", "PEAS", "PEPPER", "POTATO", "TOMATO", "VEGETABLES", 
        "APPLE", "BANANA", "GRAPES", "LEMON", "ORANGE", "PEACH", "PEAR", "PINEAPPLE", 
        "STRAWBERRY", "WATERMELON", "EGG", "FISH", "FRIED EGG", "HAM", "MEAT", 
        "PORK MEAT", "ROAST CHICKEN", "ROAST MEAT", "ROAST TURKEY", "SAUSAGES", "STEAK", 
        "BEER", "CHAMPAGNE", "COFFEE", "JUICE", "MILK", "SODA", "TEA", "WATER", "WINE", 
        "CAKE", "CHOCOLATE", "COOKIES", "ICE CREAM", "JAM", "JELLY", "PIE", "SUGAR", 
        "FRENCH FRIES", "FRUIT SALAD", "GREEN SALAD", "HAMBURGER", "HOT DOG", "PIZZA", 
        "SOUP", "SPAGHETTI", "BREAD", "CRACKERS", "POPCORN", "RICE", "TOAST", 
        "BUTTER", "CHEESE", "MARGARINE", "MAYONNAISE", "OIL", "OLIVE OIL", "SALT", "VINEGAR"
    ],
    "FAMILY": [
        "FAMILY", "FATHER", "DAD", "MOTHER", "MOM", "BROTHER", "SISTER", "SON", 
        "DAUGHTER", "BABY", "GRANDFATHER", "GRANDMOTHER", "GRANDSON", "GRANDDAUGHTER", 
        "UNCLE", "AUNT", "NEPHEW", "NIECE", "COUSIN", "HUSBAND", "WIFE"
    ],
    "VERBS": [
        "WORK", "DO", "COOK", "EAT", "DRINK", "SLEEP", "TYPE", "LISTEN", "WATCH", 
        "TALK", "SPEAK", "SMILE", "THINK", "STUDY", "WRITE", "READ", "TEACH", "RUN", 
        "WALK", "SWIM", "PLAY", "RIDE A BIKE", "RIDE A HORSE", "DANCE", "DRAW", "SING", "PAINT"
    ],
    "ADJECTIVES": [
        "OLD", "YOUNG", "NEW", "UGLY", "BEAUTIFUL", "HANDSOME", "GOOD LOOKING", "CHEAP", 
        "EXPENSIVE", "RICH", "POOR", "TALL", "SHORT", "LONG", "BIG", "SMALL", "THICK", 
        "THIN", "FAT", "HEAVY", "LIGHT", "COLD", "HOT", "WET", "DRY", "FULL", "EMPTY", 
        "STRONG", "WEAK", "HAPPY", "SAD", "THIRSTY", "HUNGRY", "TIRED", "RELAXED"
    ]
}