VOCABULARY = {
    "FOOD": [
        "BEANS", "BROCCOLI", "CARROTS", "CORN", "CUCUMBER", "GARLIC", "GREEN BEANS", 
        "LETTUCE", "OLIVE", "ONION", "PEAS", "PEPPER", "POTATO", "TOMATO", "VEGETABLES",
        "APPLE", "BANANA", "GRAPES", "LEMON", "ORANGE", "PEACH", "PEAR", "PINEAPPLE", 
        "STRAWBERRY", "WATERMELON", "EGG", "FISH", "FRIED EGG", "HAM", "MEAT", "PORK MEAT", 
        "ROAST CHICKEN", "ROAST MEAT", "ROAST TURKEY", "SAUSAGES", "STEAK", "BEER", 
        "CHAMPAGNE", "COFFEE", "JUICE", "MILK", "SODA", "TEA", "WATER", "WINE", "CAKE", 
        "CHOCOLATE", "COOKIES", "ICE CREAM", "JAM", "JELLY", "PIE", "SUGAR", "FRENCH FRIES", 
        "FRUIT SALAD", "GREEN SALAD", "HAMBURGER", "HOT DOG", "PIZZA", "SOUP", "SPAGHETTI", 
        "BREAD", "CRACKERS", "POPCORN", "RICE", "TOAST", "BUTTER", "CHEESE", "MARGARINE", 
        "MAYONNAISE", "OIL", "OLIVE OIL", "SALT", "VINEGAR"
    ],
    "FAMILY": [
        "FAMILY", "FATHER", "DAD", "MOTHER", "MOM", "BROTHER", "SISTER", "SON", "DAUGHTER", 
        "BABY", "GRANDFATHER", "GRANDMOTHER", "GRANDSON", "GRANDDAUGHTER", "UNCLE", "AUNT", 
        "NEPHEW", "NIECE", "COUSIN", "HUSBAND", "WIFE"
    ],
    "VERBS": [
        "WORK", "DO", "COOK", "EAT", "DRINK", "SLEEP", "TYPE", "LISTEN", "WATCH", "TALK", 
        "SPEAK", "SMILE", "THINK", "STUDY", "WRITE", "READ", "TEACH", "RUN", "WALK", "SWIM", 
        "PLAY", "RIDE A BIKE", "RIDE A HORSE", "DANCE", "DRAW", "SING", "PAINT"
    ],
    "ADJECTIVES": [
        "OLD", "YOUNG", "NEW", "UGLY", "BEAUTIFUL", "HANDSOME", "GOOD LOOKING", "CHEAP", 
        "EXPENSIVE", "RICH", "POOR", "TALL", "SHORT", "LONG", "BIG", "SMALL", "THICK", 
        "THIN", "FAT", "HEAVY", "LIGHT", "COLD", "HOT", "WET", "DRY", "FULL", "EMPTY", 
        "STRONG", "WEAK", "HAPPY", "SAD", "THIRSTY", "HUNGRY", "TIRED", "RELAXED"
    ]
}